#!/bin/sh
echo "ADDCAR TEAM: A, CAR: 20, SPEED: 30, CONSUMPTION: 0.04, RELIABILITY: 95" > my_pipe
echo "ADDCAR TEAM: B, CAR: 01, SPEED: 38, CONSUMPTION: 0.08, RELIABILITY: 92" > my_pipe
echo "ADDCAR TEAM: A, CAR: 03, SPEED: 27, CONSUMPTION: 0.03, RELIABILITY: 98" > my_pipe
echo "ADDCAR TEAM: C, CAR: 92, SPEED: 36, CONSUMPTION: 0.035, RELIABILITY: 84" > my_pipe
echo "ADDCAR TEAM: D, CAR: 111, SPEED: 19, CONSUMPTION: 0.01, RELIABILITY: 96" > my_pipe
echo "ADDCAR TEAM: E, CAR: 81, SPEED: 40, CONSUMPTION: 0.1, RELIABILITY: 86" > my_pipe
echo "ADDCAR TEAM: D, CAR: 969, SPEED: 28, CONSUMPTION: 0.08, RELIABILITY: 94" > my_pipe
echo "START RACE!" > my_pipe